# -*- coding: utf-8 -*-
"""addition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0JlZ2BGVdAmnh75y36ms27r6qOkwblk
"""

a = 10
b = 20
print(a+b)